export type Stage = "infant" | "toddler" | "early" | "middle";
export type Kind = "book" | "video";
export type Language = "ko" | "en";

export interface ContentItem {
  id: string;
  kind: Kind;
  title: string;
  creator: string;
  stage: Stage;
  ages: string;
  emoji: string;
  hue: number;
  summary: string;
  why: string;
  tags: string[];
  videoUrl?: string;
  coverUrl?: string;
  mustRead?: boolean;
  language?: Language;
}

export const STAGES: { id: Stage; label: string; ages: string; desc: string; emoji: string }[] = [
  { id: "infant", label: "영아", ages: "0–2세", desc: "오감 자극과 애착 형성", emoji: "🧸" },
  { id: "toddler", label: "유아", ages: "3–5세", desc: "상상력과 언어 폭발기", emoji: "🎨" },
  { id: "early", label: "저학년", ages: "6–8세", desc: "읽기 독립과 호기심", emoji: "📖" },
  { id: "middle", label: "고학년", ages: "9–12세", desc: "비판적 사고와 가치관", emoji: "🌱" },
];

export const CONTENT: ContentItem[] = [
  {
    id: "b-bear-hunt",
    kind: "book",
    title: "곰 사냥을 떠나자",
    creator: "마이클 로젠 · 헬린 옥슨버리",
    stage: "infant",
    ages: "0–3세",
    emoji: "🐻",
    hue: 80,
    summary: "리듬감 있는 반복 문장으로 가족이 함께 모험을 떠나는 그림책.",
    why: "운율과 의성어가 아기의 청각과 언어 감각을 자극합니다. 부모와 함께 읽으며 애착을 다질 수 있는 클래식.",
    tags: ["그림책", "리듬", "애착"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780689815812-L.jpg",
    mustRead: true,
  },
  {
    id: "b-very-hungry",
    kind: "book",
    title: "배고픈 애벌레",
    creator: "에릭 칼",
    stage: "infant",
    ages: "1–3세",
    emoji: "🐛",
    hue: 120,
    summary: "구멍 뚫린 페이지로 요일과 숫자, 변태 과정을 만나는 명작.",
    why: "촉감 책 요소와 색감이 풍부해 시각 발달에 도움됩니다.",
    tags: ["그림책", "감각", "수세기"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780399226908-L.jpg",
    mustRead: true,
  },
  {
    id: "v-pinkfong-baby",
    kind: "video",
    title: "핑크퐁 베이비 클래식",
    creator: "핑크퐁",
    stage: "infant",
    ages: "0–2세",
    emoji: "🎵",
    hue: 320,
    summary: "차분한 클래식 선율과 부드러운 색감으로 구성된 영상.",
    why: "자극적이지 않은 화면 전환과 음악이 영아의 정서 안정에 도움됩니다.",
    tags: ["음악", "정서"],
    videoUrl: "https://www.youtube.com/results?search_query=pinkfong+baby+classic",
  },
  {
    id: "b-where-wild",
    kind: "book",
    title: "괴물들이 사는 나라",
    creator: "모리스 센닥",
    stage: "toddler",
    ages: "3–6세",
    emoji: "👹",
    hue: 30,
    summary: "맥스가 상상의 섬에서 괴물들의 왕이 되는 환상 모험.",
    why: "분노와 외로움 같은 복잡한 감정을 다루며 정서 조절 능력을 길러줍니다.",
    tags: ["감정", "상상력"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780064431781-L.jpg",
    mustRead: true,
  },
  {
    id: "b-frog-toad",
    kind: "book",
    title: "개구리와 두꺼비는 친구",
    creator: "아놀드 로벨",
    stage: "toddler",
    ages: "4–7세",
    emoji: "🐸",
    hue: 140,
    summary: "다섯 가지 짧은 이야기 속 우정을 그린 따뜻한 동화.",
    why: "쉬운 문장으로 우정과 배려를 자연스럽게 익힐 수 있습니다.",
    tags: ["우정", "동화"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780064440202-L.jpg",
    mustRead: true,
  },
  {
    id: "v-pororo-safety",
    kind: "video",
    title: "뽀로로 안전 교육",
    creator: "뽀로로",
    stage: "toddler",
    ages: "3–5세",
    emoji: "🚦",
    hue: 210,
    summary: "친근한 캐릭터와 함께 배우는 생활 안전 수칙.",
    why: "반복적인 노래와 상황극으로 안전 규칙을 자연스럽게 익힙니다.",
    tags: ["안전", "생활"],
    videoUrl: "https://www.youtube.com/results?search_query=뽀로로+안전",
  },
  {
    id: "b-magic-tree",
    kind: "book",
    title: "마법의 시간여행",
    creator: "메리 폽 어즈번",
    stage: "early",
    ages: "6–9세",
    emoji: "🌳",
    hue: 160,
    summary: "잭과 애니가 마법 나무집을 타고 떠나는 역사·자연 시리즈.",
    why: "재미있는 모험과 함께 다양한 시대·문화 지식을 흡수합니다.",
    tags: ["모험", "지식", "시리즈"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780679824114-L.jpg",
  },
  {
    id: "b-charlotte",
    kind: "book",
    title: "샬롯의 거미줄",
    creator: "E. B. 화이트",
    stage: "early",
    ages: "7–10세",
    emoji: "🕸️",
    hue: 280,
    summary: "거미 샬롯과 아기 돼지 윌버의 잊지 못할 우정 이야기.",
    why: "생명과 죽음, 우정의 의미를 부드럽게 다루어 정서 성장을 돕습니다.",
    tags: ["우정", "고전"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780064400558-L.jpg",
    mustRead: true,
  },
  {
    id: "v-ebs-science",
    kind: "video",
    title: "EBS 과학 다큐 키즈",
    creator: "EBS",
    stage: "early",
    ages: "6–9세",
    emoji: "🔬",
    hue: 200,
    summary: "일상 속 호기심을 풀어주는 짧은 과학 다큐멘터리.",
    why: "공교육 기반의 검증된 콘텐츠로 탐구력을 키워줍니다.",
    tags: ["과학", "다큐"],
    videoUrl: "https://www.ebs.co.kr/",
  },
  {
    id: "b-wonder",
    kind: "book",
    title: "원더 (Wonder)",
    creator: "R. J. 팔라시오",
    stage: "middle",
    ages: "9–12세",
    emoji: "🌟",
    hue: 50,
    summary: "안면 기형을 가진 어기가 학교에서 친구를 만들어가는 이야기.",
    why: "공감과 다양성 존중을 깊이 있게 배울 수 있는 현대 고전.",
    tags: ["공감", "성장"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780375869020-L.jpg",
    mustRead: true,
  },
  {
    id: "b-mrs-frisby",
    kind: "book",
    title: "프리스비 부인과 니임의 쥐",
    creator: "로버트 오브라이언",
    stage: "middle",
    ages: "9–12세",
    emoji: "🐭",
    hue: 20,
    summary: "지능을 갖게 된 쥐들의 공동체를 그린 뉴베리 수상작.",
    why: "윤리와 과학기술의 관계를 사유하게 만드는 깊이 있는 작품.",
    tags: ["뉴베리", "사고력"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780689710681-L.jpg",
  },
  {
    id: "v-nat-geo-kids",
    kind: "video",
    title: "내셔널 지오그래픽 키즈",
    creator: "Nat Geo Kids",
    stage: "middle",
    ages: "8–12세",
    emoji: "🌍",
    hue: 220,
    summary: "세계 자연·동물·환경을 다루는 고품질 다큐 시리즈.",
    why: "신뢰할 수 있는 글로벌 미디어로 세계관을 넓힐 수 있습니다.",
    tags: ["자연", "다큐"],
    videoUrl: "https://kids.nationalgeographic.com/",
  },
  {
    id: "b-en-brown-bear",
    kind: "book",
    title: "Brown Bear, Brown Bear, What Do You See?",
    creator: "Bill Martin Jr. & Eric Carle",
    stage: "infant",
    ages: "0–3",
    emoji: "🐻",
    hue: 30,
    summary: "A rhythmic, repetitive English classic introducing colors and animals.",
    why: "Simple repetition and predictable patterns build early English listening and vocabulary.",
    tags: ["picture book", "colors", "rhyme"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780805047905-L.jpg",
    mustRead: true,
    language: "en",
  },
  {
    id: "b-en-goodnight-moon",
    kind: "book",
    title: "Goodnight Moon",
    creator: "Margaret Wise Brown",
    stage: "infant",
    ages: "0–3",
    emoji: "🌙",
    hue: 240,
    summary: "A gentle bedtime poem that says goodnight to everything in the great green room.",
    why: "Soothing rhythm and soft illustrations make it a perfect English bedtime read.",
    tags: ["bedtime", "classic"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780064430173-L.jpg",
    mustRead: true,
    language: "en",
  },
  {
    id: "b-en-green-eggs",
    kind: "book",
    title: "Green Eggs and Ham",
    creator: "Dr. Seuss",
    stage: "toddler",
    ages: "3–6",
    emoji: "🍳",
    hue: 130,
    summary: "Sam-I-Am insists his friend try a very unusual meal in this beloved Dr. Seuss tale.",
    why: "Only 50 simple words — perfect for early English readers and read-aloud fun.",
    tags: ["rhyme", "early reader"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780394800165-L.jpg",
    mustRead: true,
    language: "en",
  },
  {
    id: "b-en-harry-potter",
    kind: "book",
    title: "Harry Potter and the Sorcerer's Stone",
    creator: "J. K. Rowling",
    stage: "middle",
    ages: "9–12",
    emoji: "⚡",
    hue: 280,
    summary: "An orphan boy discovers he is a wizard and steps into a magical new world.",
    why: "A gateway to chapter-book reading in English with rich vocabulary and immersive world-building.",
    tags: ["fantasy", "series"],
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg",
    mustRead: true,
    language: "en",
  },
  {
    id: "v-en-cocomelon",
    kind: "video",
    title: "CoComelon Nursery Rhymes",
    creator: "CoComelon",
    stage: "infant",
    ages: "1–3",
    emoji: "🎶",
    hue: 200,
    summary: "Classic English nursery rhymes animated with bright, friendly characters.",
    why: "Repetitive lyrics and clear pronunciation help build early English listening.",
    tags: ["nursery rhymes", "music"],
    videoUrl: "https://www.youtube.com/@CoComelon",
    language: "en",
  },
  {
    id: "v-en-sesame",
    kind: "video",
    title: "Sesame Street",
    creator: "Sesame Workshop",
    stage: "toddler",
    ages: "3–6",
    emoji: "🧮",
    hue: 50,
    summary: "Educational sketches with Elmo, Big Bird, and friends teaching letters, numbers, and social skills.",
    why: "Decades of research-backed early learning in clear, natural English.",
    tags: ["education", "classic"],
    videoUrl: "https://www.youtube.com/@SesameStreet",
    language: "en",
  },
  {
    id: "v-en-bluey",
    kind: "video",
    title: "Bluey",
    creator: "BBC / Ludo Studio",
    stage: "early",
    ages: "5–9",
    emoji: "🐶",
    hue: 210,
    summary: "A playful Blue Heeler puppy and her family turn everyday life into imaginative games.",
    why: "Warm family dynamics and natural Australian English make it both entertaining and language-rich.",
    tags: ["family", "imagination"],
    videoUrl: "https://www.youtube.com/@officialblueytv",
    language: "en",
  },
  // ===== KO · infant =====
  { id: "b-ko-moon-hi", kind: "book", title: "달님 안녕", creator: "하야시 아키코", stage: "infant", ages: "0–3세", emoji: "🌙", hue: 250, summary: "달님에게 인사하는 부드러운 그림책.", why: "큰 그림과 짧은 문장으로 영아의 시지각을 자극합니다.", tags: ["그림책", "잠자리"], mustRead: true },
  { id: "b-ko-apple-thump", kind: "book", title: "사과가 쿵!", creator: "다다 히로시", stage: "infant", ages: "1–3세", emoji: "🍎", hue: 20, summary: "사과 하나로 모여드는 동물들의 이야기.", why: "반복되는 의성어가 아기의 언어 감각을 키워줍니다.", tags: ["의성어", "동물"] },
  { id: "b-ko-who-poop", kind: "book", title: "누가 내 머리에 똥 쌌어?", creator: "베르너 홀츠바르트", stage: "infant", ages: "2–4세", emoji: "💩", hue: 40, summary: "두더지가 자기 머리에 똥 싼 범인을 찾아 떠나는 유쾌한 이야기.", why: "유머와 동물 지식을 함께 즐길 수 있어요.", tags: ["유머", "동물"] },
  { id: "b-ko-peekaboo", kind: "book", title: "달걀 형제", creator: "신순재", stage: "infant", ages: "1–3세", emoji: "🥚", hue: 60, summary: "알에서 깨어나는 형제들의 따뜻한 그림책.", why: "단순한 구성과 큰 그림이 영아 발달에 적합합니다.", tags: ["그림책", "감각"] },
  { id: "b-ko-touch-touch", kind: "book", title: "토닥토닥", creator: "박은영", stage: "infant", ages: "0–2세", emoji: "🤗", hue: 350, summary: "부드러운 손길과 따뜻한 말로 가득한 애착 그림책.", why: "부모와 함께 읽으며 정서적 안정을 다집니다.", tags: ["애착", "정서"] },

  // ===== KO · toddler =====
  { id: "b-ko-doggy-poo", kind: "book", title: "강아지똥", creator: "권정생", stage: "toddler", ages: "4–7세", emoji: "🐶", hue: 80, summary: "쓸모없어 보이던 강아지똥이 민들레꽃을 피우는 이야기.", why: "생명과 존재의 의미를 따뜻하게 전합니다.", tags: ["고전", "생명"], mustRead: true },
  { id: "b-ko-cloud-bread", kind: "book", title: "구름빵", creator: "백희나", stage: "toddler", ages: "3–6세", emoji: "☁️", hue: 220, summary: "구름으로 만든 빵을 먹고 하늘을 나는 남매의 모험.", why: "독창적 일러스트와 상상력으로 큰 사랑을 받은 작품.", tags: ["상상력", "가족"], mustRead: true },
  { id: "b-ko-candy", kind: "book", title: "알사탕", creator: "백희나", stage: "toddler", ages: "4–7세", emoji: "🍬", hue: 320, summary: "신비한 알사탕을 먹으면 들리지 않던 소리가 들리는 이야기.", why: "외로움과 소통의 의미를 섬세하게 보여줍니다.", tags: ["감정", "공감"] },
  { id: "b-ko-rainbow-fish", kind: "book", title: "무지개 물고기", creator: "마르쿠스 피스터", stage: "toddler", ages: "3–6세", emoji: "🐟", hue: 200, summary: "반짝이는 비늘을 친구들과 나누는 무지개 물고기.", why: "나눔과 우정의 가치를 자연스럽게 배워요.", tags: ["우정", "나눔"] },
  { id: "b-ko-mom-angry", kind: "book", title: "엄마가 화났다", creator: "최숙희", stage: "toddler", ages: "4–7세", emoji: "😤", hue: 0, summary: "엄마의 화난 목소리에 산산이 흩어진 아이의 마음.", why: "감정 표현과 회복의 과정을 그림으로 보여줍니다.", tags: ["감정", "가족"] },

  // ===== KO · early =====
  { id: "b-ko-manbok", kind: "book", title: "만복이네 떡집", creator: "김리리", stage: "early", ages: "7–10세", emoji: "🍡", hue: 30, summary: "이상한 떡을 먹으면 신비한 일이 벌어지는 만복이의 이야기.", why: "재미있는 판타지로 읽기 독립에 좋은 챕터북.", tags: ["챕터북", "한국"], mustRead: true },
  { id: "b-ko-magic-cha", kind: "book", title: "마법천자문 1", creator: "시리얼", stage: "early", ages: "7–10세", emoji: "🐉", hue: 350, summary: "한자를 배우며 모험을 떠나는 인기 학습 만화.", why: "학습과 흥미를 동시에 잡는 베스트셀러.", tags: ["학습만화", "한자"] },
  { id: "b-ko-trash-king", kind: "book", title: "쓰레기 마을의 비밀", creator: "임지윤", stage: "early", ages: "8–10세", emoji: "♻️", hue: 130, summary: "쓰레기 마을에서 벌어지는 환경 미스터리.", why: "환경 감수성을 키우는 한국 창작 동화.", tags: ["환경", "미스터리"] },
  { id: "b-ko-school-bus", kind: "book", title: "신통방통 그림책 학교", creator: "박현숙", stage: "early", ages: "6–9세", emoji: "🚌", hue: 50, summary: "그림책 속 인물들이 학교에 모인 유쾌한 이야기.", why: "한국 초등 저학년에게 친숙한 학교 일상을 다룹니다.", tags: ["학교", "유머"] },
  { id: "b-ko-witch-bread", kind: "book", title: "마녀 위니", creator: "밸러리 토머스", stage: "early", ages: "6–9세", emoji: "🧙", hue: 280, summary: "엉뚱한 마녀 위니와 고양이 윌버의 좌충우돌 이야기.", why: "유쾌한 그림과 짧은 챕터로 읽기 즐거움을 키워요.", tags: ["판타지", "유머"] },

  // ===== KO · middle =====
  { id: "b-ko-little-prince", kind: "book", title: "어린 왕자", creator: "생텍쥐페리", stage: "middle", ages: "10–12세", emoji: "👑", hue: 220, summary: "사막에서 어린 왕자를 만난 비행사의 철학 동화.", why: "관계와 본질에 대해 평생 다시 읽게 되는 고전.", tags: ["고전", "철학"], mustRead: true },
  { id: "b-ko-momo", kind: "book", title: "모모", creator: "미하엘 엔데", stage: "middle", ages: "10–12세", emoji: "⏳", hue: 30, summary: "시간을 훔치는 회색 신사들과 맞서는 모모의 이야기.", why: "시간과 우정에 대해 깊이 사유하게 만듭니다.", tags: ["철학", "성장"] },
  { id: "b-ko-seagull", kind: "book", title: "갈매기의 꿈", creator: "리처드 바크", stage: "middle", ages: "10–12세", emoji: "🕊️", hue: 200, summary: "더 높이 날기를 꿈꾸는 갈매기 조나단의 이야기.", why: "꿈과 자아실현에 대한 짧지만 강렬한 우화.", tags: ["고전", "성장"] },
  { id: "b-ko-haeju", kind: "book", title: "해를 품은 달의 아이들", creator: "이금이", stage: "middle", ages: "10–12세", emoji: "☀️", hue: 40, summary: "한국 창작 청소년 소설.", why: "또래의 고민과 성장통을 섬세하게 그립니다.", tags: ["한국", "성장"] },
  { id: "b-ko-narnia", kind: "book", title: "나니아 연대기: 사자, 마녀 그리고 옷장", creator: "C. S. 루이스", stage: "middle", ages: "9–12세", emoji: "🦁", hue: 60, summary: "옷장 너머의 환상 세계 나니아로 떠나는 모험.", why: "고전 판타지로 깊은 상상력을 키워줍니다.", tags: ["판타지", "고전"], mustRead: true },

  // ===== EN · infant =====
  { id: "b-en-spot", kind: "book", title: "Where's Spot?", creator: "Eric Hill", stage: "infant", ages: "0–3", emoji: "🐶", hue: 50, summary: "Lift-the-flap classic following a mother dog searching for her puppy.", why: "Interactive flaps build fine motor skills and predictability.", tags: ["lift-the-flap", "interactive"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780723263661-L.jpg", language: "en" },
  { id: "b-en-snowy", kind: "book", title: "The Snowy Day", creator: "Ezra Jack Keats", stage: "infant", ages: "2–5", emoji: "❄️", hue: 210, summary: "Peter explores his neighborhood after the first snow of the season.", why: "Caldecott classic with quiet pacing perfect for early listeners.", tags: ["classic", "seasons"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780670867332-L.jpg", language: "en", mustRead: true },
  { id: "b-en-llama", kind: "book", title: "Llama Llama Red Pajama", creator: "Anna Dewdney", stage: "infant", ages: "1–3", emoji: "🦙", hue: 350, summary: "Baby llama misses Mama at bedtime in this rhyming favorite.", why: "Comforting rhymes for separation anxiety and bedtime routines.", tags: ["bedtime", "rhyme"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780670059836-L.jpg", language: "en" },
  { id: "b-en-guess", kind: "book", title: "Guess How Much I Love You", creator: "Sam McBratney", stage: "infant", ages: "1–4", emoji: "🐰", hue: 130, summary: "A tender story between Little Nutbrown Hare and Big Nutbrown Hare.", why: "Builds early vocabulary for love, comparison, and family bonds.", tags: ["love", "bedtime"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780763642648-L.jpg", language: "en" },

  // ===== EN · toddler =====
  { id: "b-en-gruffalo", kind: "book", title: "The Gruffalo", creator: "Julia Donaldson", stage: "toddler", ages: "3–6", emoji: "👾", hue: 80, summary: "A clever mouse outwits forest predators by inventing a monster.", why: "Rhythmic rhyme and clever plotting make it a read-aloud favorite.", tags: ["rhyme", "clever"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780142403877-L.jpg", language: "en", mustRead: true },
  { id: "b-en-corduroy", kind: "book", title: "Corduroy", creator: "Don Freeman", stage: "toddler", ages: "3–6", emoji: "🧸", hue: 30, summary: "A department-store teddy bear searches for his missing button.", why: "Gentle story about belonging, kindness, and friendship.", tags: ["friendship", "classic"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780670241330-L.jpg", language: "en" },
  { id: "b-en-cat-hat", kind: "book", title: "The Cat in the Hat", creator: "Dr. Seuss", stage: "toddler", ages: "4–7", emoji: "🎩", hue: 0, summary: "A mischievous cat brings chaos and fun to a rainy day.", why: "Bouncy rhyme and a limited vocabulary perfect for emerging readers.", tags: ["rhyme", "early reader"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780394800011-L.jpg", language: "en" },
  { id: "b-en-madeline", kind: "book", title: "Madeline", creator: "Ludwig Bemelmans", stage: "toddler", ages: "3–6", emoji: "👧", hue: 320, summary: "The smallest girl in a Parisian boarding school faces a sudden adventure.", why: "Classic rhyme and rich illustrations build cultural curiosity.", tags: ["classic", "rhyme"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780670445806-L.jpg", language: "en" },
  { id: "b-en-curious", kind: "book", title: "Curious George", creator: "H. A. Rey", stage: "toddler", ages: "3–6", emoji: "🐵", hue: 50, summary: "A curious little monkey's adventures with the Man with the Yellow Hat.", why: "Friendly mischief that sparks problem-solving conversations.", tags: ["classic", "curiosity"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780395150238-L.jpg", language: "en" },

  // ===== EN · early =====
  { id: "b-en-frog-toad", kind: "book", title: "Frog and Toad Are Friends", creator: "Arnold Lobel", stage: "early", ages: "6–9", emoji: "🐸", hue: 140, summary: "Five short stories about the warm friendship between Frog and Toad.", why: "Classic I Can Read series — gentle humor and easy sentences.", tags: ["friendship", "early reader"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780064440202-L.jpg", language: "en", mustRead: true },
  { id: "b-en-magic-tree-en", kind: "book", title: "Magic Tree House: Dinosaurs Before Dark", creator: "Mary Pope Osborne", stage: "early", ages: "6–9", emoji: "🌳", hue: 160, summary: "Jack and Annie's first time-traveling adventure to the age of dinosaurs.", why: "A perfect bridge into chapter books with light history and adventure.", tags: ["chapter book", "adventure"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780679824114-L.jpg", language: "en" },
  { id: "b-en-junie", kind: "book", title: "Junie B. Jones and the Stupid Smelly Bus", creator: "Barbara Park", stage: "early", ages: "6–9", emoji: "🚌", hue: 50, summary: "Spunky Junie B. navigates her first day of kindergarten her own way.", why: "Voice-driven humor that makes early chapter books irresistible.", tags: ["humor", "chapter book"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780679826422-L.jpg", language: "en" },
  { id: "b-en-ramona", kind: "book", title: "Ramona Quimby, Age 8", creator: "Beverly Cleary", stage: "early", ages: "7–10", emoji: "📚", hue: 20, summary: "Ramona faces the big-kid world of third grade with humor and heart.", why: "Newbery Honor classic with realistic family and school moments.", tags: ["Newbery", "family"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780688004774-L.jpg", language: "en", mustRead: true },
  { id: "b-en-bfg", kind: "book", title: "The BFG", creator: "Roald Dahl", stage: "early", ages: "7–10", emoji: "👁️", hue: 280, summary: "A girl named Sophie and the Big Friendly Giant team up against mean giants.", why: "Dahl's playful language and big imagination stretch growing readers.", tags: ["fantasy", "Dahl"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780142410387-L.jpg", language: "en" },
  { id: "b-en-charlottes-web-en", kind: "book", title: "Charlotte's Web", creator: "E. B. White", stage: "early", ages: "8–10", emoji: "🕸️", hue: 120, summary: "The unforgettable friendship between Wilbur the pig and Charlotte the spider.", why: "A timeless story of friendship, life, and loss for early readers.", tags: ["classic", "friendship"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780064400558-L.jpg", language: "en", mustRead: true },

  // ===== EN · middle =====
  { id: "b-en-holes", kind: "book", title: "Holes", creator: "Louis Sachar", stage: "middle", ages: "10–12", emoji: "🕳️", hue: 30, summary: "Stanley Yelnats digs holes at a desert camp — and uncovers a generations-old mystery.", why: "Newbery Medal-winning structure with humor, history, and grit.", tags: ["Newbery", "mystery"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780440414803-L.jpg", language: "en", mustRead: true },
  { id: "b-en-lightning", kind: "book", title: "Percy Jackson: The Lightning Thief", creator: "Rick Riordan", stage: "middle", ages: "9–12", emoji: "⚡", hue: 220, summary: "A twelve-year-old discovers he's the son of a Greek god — and a thief.", why: "Action-packed gateway into mythology for upper-elementary readers.", tags: ["fantasy", "mythology"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780786838653-L.jpg", language: "en" },
  { id: "b-en-wrinkle", kind: "book", title: "A Wrinkle in Time", creator: "Madeleine L'Engle", stage: "middle", ages: "10–12", emoji: "🌌", hue: 260, summary: "Meg, Charles Wallace, and Calvin travel through space and time to rescue their father.", why: "Newbery-winning sci-fi that blends science, family, and courage.", tags: ["Newbery", "sci-fi"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780312367541-L.jpg", language: "en" },
  { id: "b-en-giver", kind: "book", title: "The Giver", creator: "Lois Lowry", stage: "middle", ages: "10–12", emoji: "🎁", hue: 200, summary: "In a society of sameness, Jonas is chosen to receive the memories of the past.", why: "Newbery Medal dystopia that opens deep discussions about freedom and feeling.", tags: ["Newbery", "dystopia"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780544336261-L.jpg", language: "en" },
  { id: "b-en-terabithia", kind: "book", title: "Bridge to Terabithia", creator: "Katherine Paterson", stage: "middle", ages: "10–12", emoji: "🌉", hue: 140, summary: "Two outsider friends invent a magical kingdom — until tragedy reshapes everything.", why: "A powerful Newbery story about friendship, imagination, and grief.", tags: ["Newbery", "friendship"], coverUrl: "https://covers.openlibrary.org/b/isbn/9780064401845-L.jpg", language: "en" },
];

export function libraryLinks(title: string) {
  const q = encodeURIComponent(title);
  return [
    { name: "국립중앙도서관", url: `https://www.nl.go.kr/NL/contents/search.do?kwd=${q}` },
    { name: "서울도서관", url: `https://elib.seoul.go.kr/contents/search.do?query=${q}` },
    { name: "교보문고", url: `https://search.kyobobook.co.kr/search?keyword=${q}` },
  ];
}